### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by droperdu** [Joseloll/Fake-Roblox-Image-Logger-Website#7]
doesnt really work

**Comment by Joseloll** [comment]
Ok l will update soon

**Comment by Ml2x** [comment]
bro i just maked it like in description and how to launch it?

**Comment by Joseloll** [comment]
there I made it more simple

**Comment by Joseloll** [comment]
and updated it

**Comment by Ml2x** [comment]
just made vid tut please

**Comment by Ml2x** [comment]
doesnt work
